# postgre com postgis
postgis:
    container_name: ${PROJECT_NAME}_postgis
    image: postgis/postgis
    volumes:
        - ${DB_DATA}:/var/lib/postgresql/data
    ports:
        - ${DB_PORT}:5432
    environment:
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_USER:     ${DB_USER}
        POSTGRES_DB:       ${DB_NAME}

# geoserver
geoserver:
    container_name: ${PROJECT_NAME}_geoserver
    build: ./docker-assets/geoserver
    volumes:
       - ${GEOSERVER_DATA}:/geoserver_data/data
       - /var/run/docker.sock:/var/run/docker.sock
    ports:
        - ${GEOSERVER_PORT}:8080
        - 22:22
    links:
        - postgis

# geonetwork
geonetwork:
   container_name: ${PROJECT_NAME}_geonetwork
   image: geonetwork:3.10.5
   ports:
       - ${GEONETWORK_PORT}:8080
   environment:
       DATA_DIR: /var/lib/geonetwork_data
   volumes:
       - ${GEONETWORK_DATA}:/var/lib/geonetwork_data
